title: Esteban G. (@cordutie)
logo: /assets/img/logo.jpeg
description: Place to leave stuff I've done so I don't forget about them.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
