# _config.yml
title: Your Website Title
description: >-
  A simple description of your site. This will appear in search engine results.
author: Your Name
github:
  is_project_page: false
show_downloads: true
theme: jekyll-theme-minimal

# Optional settings for social links
social_links:
  twitter: your_twitter_handle
  github: your_github_username
  linkedin: your_linkedin_profile

# Additional sections
education:
  - degree: PhD in Computer Science
    institution: Example University
    year: 2025
  - degree: MSc in Mathematics
    institution: Sample Institute
    year: 2023

publications:
  - title: "Deep Learning for Audio Generation"
    authors: "Your Name, Co-author Name"
    journal: "Journal of AI Research"
    year: 2024
  - title: "Fourier Transforms in Modern AI"
    authors: "Your Name"
    journal: "Mathematics Today"
    year: 2023

music:
  - album: "Synthetic Waves"
    artist: "Your Name"
    year: 2022
  - album: "Abstract Soundscapes"
    artist: "Your Name"
    year: 2020

others:
  - item: "Conference Speaker at AI Summit 2024"
  - item: "Open-source contributor to ML projects"

#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
